const OrderActionTypes = {
    FETCH_LOGISTICS: "FETCH_LOGISTICS",
    
    FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
    FETCH_ALL_ORDERS_FAIL: "FETCH_ALL_ORDERS_FAIL",

    FETCH_COMPLETE_ORDERS_SUCCESS: "FETCH_COMPLETE_ORDERS_SUCCESS",
    FETCH_COMPLETE_ORDERS_FAIL: "FETCH_COMPLETE_ORDERS_FAIL",

    FETCH_INCOMPLETE_ORDERS_SUCCESS: "FETCH_INCOMPLETE_ORDERS_SUCCESS",
    FETCH_INCOMPLETE_ORDERS_FAIL: "FETCH_INCOMPLETE_ORDERS_FAIL",

    FETCH_ALL_CUSTOMERS_SUCCESS: "FETCH_ALL_CUSTOMERS_SUCCESS",
    FETCH_TOTAL_REVENUE_SUCCESS: "FETCH_TOTAL_REVENUE_SUCCESS",
};
  
export default OrderActionTypes;
  