const OrderActionTypes = {
    FETCH_ALL_ORDERS: "FETCH_ALL_ORDERS",
    FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
    FETCH_ALL_ORDERS_FAIL: "FETCH_ALL_ORDERS_FAIL",

    FETCH_COMPLETE_ORDERS: "FETCH_COMPLETE_ORDERS",
    FETCH_COMPLETE_ORDERS_SUCCESS: "FETCH_COMPLETE_ORDERS_SUCCESS",
    FETCH_COMPLETE_ORDERS_FAIL: "FETCH_COMPLETE_ORDERS_FAIL",

    FETCH_INCOMPLETE_ORDERS: "FETCH_INCOMPLETE_ORDERS",
    FETCH_INCOMPLETE_ORDERS_SUCCESS: "FETCH_INCOMPLETE_ORDERS_SUCCESS",
    FETCH_INCOMPLETE_ORDERS_FAIL: "FETCH_INCOMPLETE_ORDERS_FAIL",
};
  
export default OrderActionTypes;
  