const InventoryActionTypes = {
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    UPDATE_IMAGES_TO_UPLOAD: "UPDATE_IMAGES_TO_UPLOAD",
    UPDATE_PREVIEW_IMAGE: "UPDATE_PREVIEW_IMAGE"
};
  
export default InventoryActionTypes;
  